nodeLinker: node-modules

enableGlobalCache: false

enableTelemetry: false

# Permitir scripts de postinstall para paquetes que lo requieren (Prisma descarga binarios, bcrypt compila nativos)
enableScripts: true
